### ISSUE TITLE
Error while Installing gem in Linux

### ISSUE THREAD

**Issue by maisaengineering** [tonytonyjan/exif#1]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
 
/usr/local/bin/ruby extconf.rb 
checking for main() in -lexif... no
checking for libexif/exif-data.h... no
creating Makefile
 
make "DESTDIR=" clean
 
make "DESTDIR="
compiling exif.c
In file included from exif.c:2:0:
data.h:4:31: fatal error: libexif/exif-data.h: No such file or directory
#include <libexif/exif-data.h>
^
compilation terminated.
make: *** [exif.o] Error 1
 
make failed, exit code 2

**Comment by tonytonyjan** [comment]
Have you installed `libexif`?

**Comment by tonytonyjan** [comment]
@maisaengineering have you solved?

**Comment by maisaengineering** [comment]
@tonytonyjan yes,  'libexif-devel' package helped us. Thank's for your response

**Comment by tonytonyjan** [comment]
:beers:

**Comment by maisaengineering** [comment]
:beers: :+1:

**Comment by maisaengineering** [comment]
btw, your suggestion works too. We used port install instead of homebrew where it went fine, just for the record. Thanks for the timely response!

```
$port install libexif
```
