### ISSUE TITLE
Incorrectly reporting time zone

### ISSUE THREAD

**Issue by ronald8192** [tonytonyjan/exif#10]
The program reports the current computer timezone:

I have a photo taken in GMT-4 timezone, my computer currently in GMT+8 timezone.

Code:
>  Exif::Data.new('IMG_7368.jpg').date_time

Output:
>  => 2017-06-02 12:56:26 +0800

Should be:
>  => 2017-06-02 12:56:26 -0400

**Comment by tonytonyjan** [comment]
Unfortunately, there is no standard for EXIF time zone offset. A common approach is to use its geo information to find out the time zone, however, if the image is not geo-tagged, there is no way to figure out the time zone.

**Comment by ronald8192** [comment]
Thanks for you explain!

but I have another question.
I have a photo(IMG_7313.jpg) taken in `2017-06-01 21:40:30 -0400`,
as you mentioned above, my computer is setted to GMT+8, so `Exif::Data.new('IMG_7313.jpg').date_time` output `2017-06-01 21:40:30 +0800` is expected.

But why when I set my computer timezone to GMT-4 (Toronto - Canada), `Exif::Data.new('IMG_7313.jpg').date_time` will output `2017-06-01 22:40:30 -0400`?
