### ISSUE TITLE
Exif::NotReadble error misspelled

### ISSUE THREAD

**Issue by Aupajo** [tonytonyjan/exif#14]
I'm not sure what you want to do about this one, but I got tripped up while writing an exception handler – correct spelling should be `Exif::NotReadable`. Unfortunately, you can't change this without breaking anyone's existing explicit rescues for this error, so I'm not sure it's a good idea to change.

**Comment by tonytonyjan** [comment]
Oops, thanks for this report. For compatibility, maybe we can make both `Exif::NotReadble` and`Exif::NotReadable` available.
