### ISSUE TITLE
Can't reference error classes from Exif module

### ISSUE THREAD

**Issue by ShaneBurkhart** [tonytonyjan/exif#15]
Hey there, 

I'm trying to reference Exif::Error is a rescue block:

```
      begin
        return Exif::Data.new(File.new(file_path, 'r'))
      rescue Exif::Error => e
        puts e
        return nil
      end
```

It's telling me Error isn't defined, and when I inspect the constants on Exif, only Data and Version appear.  

I'm using v2.0.1.

I noticed the error classes are being set in exif.c and being used in data.c.  My guess is this is some kind of variable issue.  Possibly that they aren't shared across files properly?  Could be wrong though.  

Thanks in advance for taking a look!

**Comment by tonytonyjan** [comment]
Sorry, I can't reproduce the same issue. Could you please give me the complete error message? And prints `Exiff::Version` as well? For exapmle:

```
require 'exif'

puts Exif::VERSION
begin
  Exif::Data.new("./not/readable")
rescue Exif::Error => e
  puts e
  nil
end
```
