### ISSUE TITLE
How to use Liquid to get the EXIF data using your exif tool?

### ISSUE THREAD

**Issue by 888ba8** [tonytonyjan/exif#26]
@tonytonyjan  How could we have a .rb plugin for Jekyll to include the EXIF data using your exif tool?

Here is something analogous for another tool called exiftag: https://github.com/benib/jekyll-exiftag/blob/master/lib/jekyll-exiftag.rb

Since it does not support PNG however, I am interested in yours! 👍

**Comment by tonytonyjan** [comment]
Hi, @888ba8, sorry for the late reply. Unfortunately, the `exif` gem does not support PNG images neither because it depends on `libexif`. Thus I would close this issue. Let me know if you need other helps with this gem, thanks! :)
