### ISSUE TITLE
Error installation on Mac Capital 10.11

### ISSUE THREAD

**Issue by thaichor** [tonytonyjan/exif#3]
I install exif and libexif successfully already. but still error with gem exif 1.0.1

```
brew install libexif
==> Downloading https://homebrew.bintray.com/bottles/libexif-0.6.21.el_capitan.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/libexif-0.6.21.el_capitan.bottle.1.tar.gz
==> Pouring libexif-0.6.21.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/libexif/0.6.21: 29 files, 864K

brew install exif
==> Downloading https://downloads.sourceforge.net/project/libexif/exif/0.6.21/exif-0.6.21.tar.gz
Already downloaded: /Library/Caches/Homebrew/exif-0.6.21.tar.gz
==> ./configure --prefix=/usr/local/Cellar/exif/0.6.21 --disable-silent-rules --disable-nls
==> make install
🍺  /usr/local/Cellar/exif/0.6.21: 8 files, 112K, built in 9 seconds
```

```
gem install exif -v '1.0.1'

Building native extensions.  This could take a while...
ERROR:  Error installing exif:
	ERROR: Failed to build gem native extension.

    /Users/thaichorseng/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20151218-8895-1342xh5.rb extconf.rb
checking for main() in -lexif... no
checking for libexif/exif-data.h... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling data.c
data.c:1:10: fatal error: 'libexif/exif-data.h' file not found
#include <libexif/exif-data.h>
         ^
1 error generated.
make: *** [data.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/thaichorseng/.rvm/gems/ruby-2.1.5@yoolk_engines/gems/exif-1.0.1 for inspection.
Results logged to /Users/thaichorseng/.rvm/gems/ruby-2.1.5@yoolk_engines/extensions/x86_64-darwin-14/2.1.0/exif-1.0.1/gem_make.out
```

**Comment by tonytonyjan** [comment]
@thaichor have you tried `CPATH` or `C_INCLUDE_PATH`?

**Comment by thaichor** [comment]
@tonytonyjan I'm sorry. I'm just a beginner in Objective C. And I don't understand what is ```CPATH``` or ```C_INCLUDE_PATH```. What can I do with it?

**Comment by tonytonyjan** [comment]
I notice that you are using homebrew, you can find location of libexif via `brew --prefix libexif`

then try `CPATH=$(brew --prefix libexif)/include gem install exif` or `C_INCLUDE_PATH =$(brew --prefix libexif)/include gem install exif` to see if it works.

**Comment by thaichor** [comment]
OMG. It works. Thanks a lot @tonytonyjan . It would be helpful if you could show me what the problem is and how does that solve it.

**Comment by tonytonyjan** [comment]
Tt's because of the C compiler can't find 'libexif/exif-data.h' in its default searching path. You have installed homebrew but I don't know why your library is not linked to your system. The environment variables `CPATH` and `C_INCLUDE_PATH` make compiler search additional paths.

You probably need more knowledge of C programming language.

good luck, I am closing this issue :smile:

**Comment by jdraths** [comment]
@tonytonyjan I've run into the same problem using Homebrew. I used CPATH like you said, which allowed me to gem install exif. But now when I try to run the rails server I get the following error:
    ```
$ rails s
/Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': dlopen(/Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/exif-1.0.1/lib/exif/exif.bundle, 9): Symbol not found: _exif_data_free (LoadError)
  Referenced from: /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/exif-1.0.1/lib/exif/exif.bundle
  Expected in: flat namespace
 in /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/exif-1.0.1/lib/exif/exif.bundle - /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/exif-1.0.1/lib/exif/exif.bundle
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/exif-1.0.1/lib/exif.rb:2:in `<top (required)>'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/roanedraths/rails_proj/daily_report/config/application.rb:7:in `<top (required)>'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/roanedraths/.rvm/gems/ruby-2.3.0@rails4.2/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by jdraths** [comment]
I ended up resolving this, but not really sure how... lot's of googling and tinkering...

**Comment by jaredgoertzen** [comment]
To get this working for me I just did `xcode-select --install` and it will install and setup the compile tools for xcode.

**Comment by adri123** [comment]
Hello,

I have the same problem as @jdraths : after succesful install of the exif library with homebrew and the gem it fails at the require step and says the error bellow

`
/Users/adri/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/adri/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/exif-1.0.1/lib/exif/exif.bundle, 9): Symbol not found: _exif_data_free (LoadError)
  Referenced from: /Users/adri/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/exif-1.0.1/lib/exif/exif.bundle
  Expected in: flat namespace
 in /Users/adri/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/exif-1.0.1/lib/exif/exif.bundle - /Users/adri/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/exif-1.0.1/lib/exif/exif.bundle
	from /Users/adri/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/adri/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/exif-1.0.1/lib/exif.rb:2:in `<top (required)>'
	from /Users/adri/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/adri/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/adri/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/adri/ruby/adri-scripts/fichiers/renome_ernest.rb:2:in `<main>'
`

any help ?

**Comment by vlasiak** [comment]
I've faced the same problem today: managed to run `bundle install` successfully by specifying compiler search paths, but couldn't do anything after that (starting rails server, running migrations, etc.)
After some period of time I've investigated that the problem actually lied in Xcode Command Line Tools. So, I removed previously installed `exif` gem, installed Xcode CLT and I've got everything worked out (even without specifying `CPATH` or `C_INCLUDE_PATH` for gem installation).
BTW, [here](http://railsapps.github.io/xcode-command-line-tools.html) you can find good guide for installing Xcode CLT.
