### ISSUE TITLE
Support reading from String

### ISSUE THREAD

**Issue by brent-clintel** [tonytonyjan/exif#5]
Just wondering if you have any plans to implement the reading from string functionality?

**Comment by chadwilken** [comment]
Are you talking about a Base64 image? It would be pretty easy to convert the base64 image to a tmpfile and then read from that. I created a `Base64Image` class that takes a string and converts it to a tmpfile.

```
require 'stringio'

class Base64Image
  attr_reader :image_string

  def initialize(image)
    @image_string = image
  end

  def to_uploaded_file(filename)
    if blob = to_blob(@image_string)
      extension = image_parts(@image_string).fetch(:extension, 'jpg')
      temp_image_file = Tempfile.new([filename, extension])
      temp_image_file.binmode
      temp_image_file << blob
      temp_image_file.rewind

      ActionDispatch::Http::UploadedFile.new(filename: "#{filename}.#{extension}", type: extension, tempfile: temp_image_file)
    end
  end

  private
    def split_base64(uri_str)
      if uri_str.match(%r{^data:(.*?);(.*?),(.*)$})
        uri = Hash.new
        uri[:type] = $1 # "image/jpeg"
        uri[:encoder] = $2 # "base64"
        uri[:data] = $3 # data string
        uri[:extension] = $1.split('/')[1] # "jpeg"
        return uri
      else
        return nil
      end
    end

    def to_blob(base64_image)
      return nil unless base64_image.try(:match, %r{^data:(?:.*?);(?:.*?),(?:.*)$})

      image_data = image_parts(base64_image).fetch(:data)
      Base64.decode64(image_data)
    end

    def image_parts(base64_image)
      @image_data ||= split_base64(base64_image)
    end
end
```

**Comment by brent-clintel** [comment]
Thanks Chad for this code.  I've got the image file data stored in a database, so all the base64 stuff and mime_type meta data has already been extracted.

It's because we store images in the DB that I don't want to have to write the data to disk just to use this library.  In another library, exifr, I was able to use the StringIO class to do this, but as this lib uses a C implementation, I'm not exactly sure how I can monkeypatch it to achieve the same results.

**Comment by Aupajo** [comment]
I have a file that's being streamed as an IO object, and I'd love to be able to use it with this gem without having to construct a Tempfile. Being able to call `Exif::Data.new(io)` would mean this library could support `STDIN`, strings (via `StringIO`), `File`, and `Pathname` objects.

I don't know much about C extensions, unfortunately, but I believe you could achieve this by replacing the call to `exif_data_new_from_file` with `exif_data_new_from_data`:

![image](https://user-images.githubusercontent.com/14123/29346975-2da1e100-829d-11e7-9ff7-6e0617903db5.png)

From http://libexif.sourceforge.net/internals/exif-data_8c.html

**Comment by Aupajo** [comment]
I've dug deeper, and I think I understand the gist of how to do this, although my lack of C knowledge  doesn't help.

In `data.c`, we call `exif_data_new_from_file` like this:

```c

VALUE rb_new(VALUE self, VALUE file_path){
  Check_Type(file_path, T_STRING);

  ExifData* ed;
  VALUE rb_data;

  ed = exif_data_new_from_file(StringValueCStr(file_path));
// ...
```

`exif_data_new_from_file` creates an `ExifLoader`, which works by storing some data in memory that gets read later by calling `exif_loader_get_data`:

```c
exif_data_new_from_file (const char *path)
{
  ExifData *edata;
  ExifLoader *loader;

  loader = exif_loader_new ();
  exif_loader_write_file (loader, path);
  edata = exif_loader_get_data (loader);
  exif_loader_unref (loader);

  return (edata);
}
```

`exif_loader_write_file` works by opening a file and reading it in 1KB chunks, and calling the lower level `exif_loader_write_data` for each chunk:

```c
exif_loader_write_file (ExifLoader *l, const char *path)
{
  FILE *f;
  int size;
  unsigned char data[1024];

  if (!l) 
          return;

  f = fopen (path, "rb");
  if (!f) {
            exif_log (l->log, EXIF_LOG_CODE_NONE, "ExifLoader",
                    _("The file '%s' could not be opened."), path);
          return;
  }
  while (1) {
            size = fread (data, 1, sizeof (data), f);
          if (size <= 0) 
                  break;
          if (!exif_loader_write (l, data, size)) 
                  break;
  }
  fclose (f);
}
```

So all we need to do to support any IO object is something like this psuedo-Ruby code:

```ruby
def initialize(string_or_io)
  if string_or_io.respond_to?(:read)
    exif_loader = exif_loader_new() # C

    read_chunks(string_or_io).each do |chunk|
      exif_loader_write(exif_loader, chunk, chunk.size) # C
    end

    exif_data = exif_loader_get_data(exif_loader) # C
    exif_loader_unref(exif_loader) # C
    exif_data
  else
    # do what we're currently doing
    exif_data_new_from_file(string_or_io) # C
  end
end
```

**Comment by Aupajo** [comment]
The spec for this is quite simple. I've added one here: https://github.com/Aupajo/exif/commit/ca9197a73c6316b38d4702bfd07ee6fad8734a0f

**Comment by tonytonyjan** [comment]
Sorry for the delayed response. I just updated this gem to v2.0.0 which supports reading from a string. With this version, you can initialize an instance by either a String or an IO object, for example:

```
Exif::Data.new(IO.read(file_path, mode: 'rb'))
Exif::Data.new(File.open(file_path))
```

To see more breaking changes, have a look at CHANGELOG.log.
